### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by CasualArclamp** [ertong/star-debug#1]
Hey there i found a few spelling and terminology errors

In the Dish and router sections the speed is given in MB/s and KB/s when it should be Mb/s and Kb/s
also in antenna angle is spelt incorrectly as agngle 
in dish single to noise is spelt wrong as signal to noice

keep up the good work guys :)

**Comment by ertong** [comment]
Thanks for reporting.

These and a bit more spelling changes: https://github.com/ertong/star-debug/commit/265fa6d642f0c2822ab61d7789a43d4eeee0281f

Will be included in the next release.
